config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'
  get 'welcome/add'

  resources :reviews
  resources :declarations
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/declaration.rb
class Declaration < ApplicationRecord
end

app/models/review.rb
class Review < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/declarations_controller.rb
class DeclarationsController < ApplicationController
  before_action :set_declaration, only: [:show, :edit, :update, :destroy]

  # GET /declarations
  # GET /declarations.json
  def index
    @declarations = Declaration.all
  end

  # GET /declarations/1
  # GET /declarations/1.json
  def show
  end

  # GET /declarations/new
  def new
    @declaration = Declaration.new
  end

  # GET /declarations/1/edit
  def edit
  end

  # POST /declarations
  # POST /declarations.json
  def create
    @declaration = Declaration.new(declaration_params)

    respond_to do |format|
      if @declaration.save
        format.html { redirect_to @declaration, notice: 'Declaration was successfully created.' }
        format.json { render :show, status: :created, location: @declaration }
      else
        format.html { render :new }
        format.json { render json: @declaration.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /declarations/1
  # PATCH/PUT /declarations/1.json
  def update
    respond_to do |format|
      if @declaration.update(declaration_params)
        format.html { redirect_to @declaration, notice: 'Declaration was successfully updated.' }
        format.json { render :show, status: :ok, location: @declaration }
      else
        format.html { render :edit }
        format.json { render json: @declaration.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /declarations/1
  # DELETE /declarations/1.json
  def destroy
    @declaration.destroy
    respond_to do |format|
      format.html { redirect_to declarations_url, notice: 'Declaration was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_declaration
      @declaration = Declaration.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def declaration_params
      params.require(:declaration).permit(:ip_address, :city, :country_name, :country_code, :latitude, :longitude, :time_zone, :image, :rawemotiondata, :email)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)

    respond_to do |format|
      if @review.save
        format.html { redirect_to @review, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:email, :fullname, :title, :body)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @countries = Declaration.limit(50).where.not(country_name: '').group(:country_name).order('count(*) DESC').pluck(:country_name)
  end

  def add
    if Rails.env.development?
      # Fake IP address in development because otherwise 127.0.0.1
     # ip_address = Faker::Internet.ip_v4_address
   # else
      ip_address = request.remote_ip
    end

    response = RestClient.get("https://freegeoip.net/json/#{ip_address}")
    response_object = JSON.load(response)

  #  ipp = Declaration.find_by ip_address: response_object.fetch('ip')
  #  if Declaration.exists?(ip_address: response_object.fetch('ip'))
    @dec = Declaration.create!(
      ip_address: response_object.fetch('ip'),
      city: response_object.fetch('city'),
      country_name: response_object.fetch('country_name'),
      country_code: response_object.fetch('country_code'),
      latitude: response_object.fetch('latitude'),
      longitude: response_object.fetch('longitude'),
      time_zone: response_object.fetch('time_zone')
    )

    render json: {clicks: Declaration.count, location: @dec.latitude + "," + @dec.longitude}
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/declarations_helper.rb
module DeclarationsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/declarations/_form.html.erb
<%= form_with(model: declaration, local: true) do |form| %>
  <% if declaration.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(declaration.errors.count, "error") %> prohibited this declaration from being saved:</h2>

      <ul>
      <% declaration.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :ip_address %>
    <%= form.text_field :ip_address, id: :declaration_ip_address %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city, id: :declaration_city %>
  </div>

  <div class="field">
    <%= form.label :country_name %>
    <%= form.text_field :country_name, id: :declaration_country_name %>
  </div>

  <div class="field">
    <%= form.label :country_code %>
    <%= form.text_field :country_code, id: :declaration_country_code %>
  </div>

  <div class="field">
    <%= form.label :latitude %>
    <%= form.text_field :latitude, id: :declaration_latitude %>
  </div>

  <div class="field">
    <%= form.label :longitude %>
    <%= form.text_field :longitude, id: :declaration_longitude %>
  </div>

  <div class="field">
    <%= form.label :time_zone %>
    <%= form.text_field :time_zone, id: :declaration_time_zone %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_field :image, id: :declaration_image %>
  </div>

  <div class="field">
    <%= form.label :rawemotiondata %>
    <%= form.text_field :rawemotiondata, id: :declaration_rawemotiondata %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :declaration_email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/declarations/edit.html.erb
<h1>Editing Declaration</h1>

<%= render 'form', declaration: @declaration %>

<%= link_to 'Show', @declaration %> |
<%= link_to 'Back', declarations_path %>

app/views/declarations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Declarations</h1>

<table>
  <thead>
    <tr>
      <th>Ip address</th>
      <th>City</th>
      <th>Country name</th>
      <th>Country code</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Time zone</th>
      <th>Image</th>
      <th>Rawemotiondata</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @declarations.each do |declaration| %>
      <tr>
        <td><%= declaration.ip_address %></td>
        <td><%= declaration.city %></td>
        <td><%= declaration.country_name %></td>
        <td><%= declaration.country_code %></td>
        <td><%= declaration.latitude %></td>
        <td><%= declaration.longitude %></td>
        <td><%= declaration.time_zone %></td>
        <td><%= declaration.image %></td>
        <td><%= declaration.rawemotiondata %></td>
        <td><%= declaration.email %></td>
        <td><%= link_to 'Show', declaration %></td>
        <td><%= link_to 'Edit', edit_declaration_path(declaration) %></td>
        <td><%= link_to 'Destroy', declaration, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Declaration', new_declaration_path %>

app/views/declarations/new.html.erb
<h1>New Declaration</h1>

<%= render 'form', declaration: @declaration %>

<%= link_to 'Back', declarations_path %>

app/views/declarations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ip address:</strong>
  <%= @declaration.ip_address %>
</p>

<p>
  <strong>City:</strong>
  <%= @declaration.city %>
</p>

<p>
  <strong>Country name:</strong>
  <%= @declaration.country_name %>
</p>

<p>
  <strong>Country code:</strong>
  <%= @declaration.country_code %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @declaration.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @declaration.longitude %>
</p>

<p>
  <strong>Time zone:</strong>
  <%= @declaration.time_zone %>
</p>

<p>
  <strong>Image:</strong>
  <%= @declaration.image %>
</p>

<p>
  <strong>Rawemotiondata:</strong>
  <%= @declaration.rawemotiondata %>
</p>

<p>
  <strong>Email:</strong>
  <%= @declaration.email %>
</p>

<%= link_to 'Edit', edit_declaration_path(@declaration) %> |
<%= link_to 'Back', declarations_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Happyearth</title>
    <%= csrf_meta_tags %>


    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://www.webglearth.com/v2/api.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/reviews/_form.html.erb
<%= form_with(model: review, local: true) do |form| %>
  <% if review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :review_email %>
  </div>

  <div class="field">
    <%= form.label :fullname %>
    <%= form.text_field :fullname, id: :review_fullname %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :review_title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_field :body, id: :review_body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reviews</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Fullname</th>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.email %></td>
        <td><%= review.fullname %></td>
        <td><%= review.title %></td>
        <td><%= review.body %></td>
        <td><%= link_to 'Show', review %></td>
        <td><%= link_to 'Edit', edit_review_path(review) %></td>
        <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_review_path %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Back', reviews_path %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @review.email %>
</p>

<p>
  <strong>Fullname:</strong>
  <%= @review.fullname %>
</p>

<p>
  <strong>Title:</strong>
  <%= @review.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @review.body %>
</p>

<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', reviews_path %>

app/views/welcome/index.html.erb
  <script type="text/javascript">
    window.locations = [
      <% Declaration.all.each do |declaration| %>
        [<%= declaration.latitude %>, <%= declaration.longitude %>],
      <% end %>
    ]
  </script>

  <div class="list-countries">
    <h1>Smiley Happy Countries</h1>
    <div>
      <ol>
        <% @countries.each do |country| %>
            <li><%= country %></li>
        <% end %>
      </ol>
    </div>
  </div>


  <div id="earth_div"></div>
  <div id="nav">
        <div class="row">
          <%= link_to "I AM HAPPY", 'javascript:void(0)', id: 'create_declaration' %> <br>
          <input type="checkbox" name="email" value="Email"> I would like to share this web to my friends. Please provide email addresses: <br>
          <textarea rows="4" cols="100">http://happyearth.today/ is fun. </textarea>
       </div>
    <div>

    </div>
  </div>